services:

  rundeck:
    build:
      context: .
      dockerfile: Containerfile.rundeck
    networks:
      - n_rundeck
    depends_on:
      - mysql
    env_file: .env 
    volumes:
      - ansible-data:/etc/ansible/
      - rundeck-home:/home/rundeck/
    ports:
      - "4440:4440"
  
  mysql:
    image: mysql:5.7
    networks:
      - n_rundeck
    env_file: .env
    volumes:
      - dbdata:/var/lib/mysql
  
  sshtest:
    build:
      context: .
      dockerfile: Containerfile.openssh
    networks:
      - n_rundeck
    ports:
      - "2222:22"

volumes:
  dbdata:
  ansible-data:
  rundeck-home:

networks:
  n_rundeck:
    external:
      name: n_rundeck
