FROM docker.io/rundeck/rundeck:5.0.0
LABEL maintaner = "Tamas Molnar <tmolnar0831@gmail.com> - https://tomsitcafe.com"
USER root
RUN apt-get update && apt-get -y install ansible python3
VOLUME ansible-data:/etc/ansible/
VOLUME rundeck-home:/home/rundeck/
EXPOSE 4440/tcp
USER rundeck